twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_3_horizontal_layout.html.twig']
    globals:
        constantes_generales: '@App\Model\ConstantesGenerales'
        APP_NAME: 'DENS'
        VERSION: '%app.version%'
        VERSION_SYMFONY:  '%app.version.symfony%'
        VERSION_DOCTRINE: '%app.version.doctrine%'
        VERSION_MYSQL: '%app.version.mysql%'

        # se pone aca por que va para el menu superior y así no hace falta pasarlo en cada controlador
        establecimiento_repository: '@App\Repository\EstablecimientoRepository'    

when@test:
    twig:
        strict_variables: true
